FROM python:3.6.4

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY ./Pipfile* /usr/src/app/
RUN pip install pipenv && pipenv install

COPY . /usr/src/app

CMD pipenv run python manage.py run -h 0.0.0.0
