FROM node:9

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV NODE_PATH=/usr/src/app/node_modules
ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY yarn.lock /usr/src/app/yarn.lock
COPY package.json /usr/src/app/package.json

RUN yarn

CMD ["yarn", "start"]
